server:
  port: 8203

mybatis-plus:
  type-enums-package: cn.itedus.ssyx.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-product?characterEncoding=utf-8&useSSL=false
    username: root
    password: 980918

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 192.168.10.101
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual


aliyun:
  endpoint: oss-cn-beijing.aliyuncs.com
  keyid: kOYsekihDnjXSW0cJFR1yHFyg9Owwu77kLdEfYkLdQE=
  keysecret: vDt0Yz9pTJdYsbae9JOivbSCbyhJ3kt5Sl8iwwbbOtA=
  bucketname: ssyx-itedus0613

